<?php
require_once ($_SERVER["DOCUMENT_ROOT"] . "/src/init.php");
$sec = "questions";
$pageTitle="Generate a new question";
if (!$session->is_logged_in()) $session->message("You must log in to submit a new question.", "", "danger");

if(isset($_POST['submit'])){

  $data = $_POST;
  $token = $data['token'];
  if(!Token::validateToken($token)){
    die(json_encode(['status' => false, 'err' => 'Token is not valid']));
  }

  unset($data['token']);
  unset($data['submit']);
  $data['uid'] = USER_ID;

  $QNA = new QNA();
  $gen = $QNA->generate_question($data);
  Redirect::RedirectTo('/questions/question.php?id='.$gen);
}
include (ROOT_PATH . 'inc/head.php');
?>
<body>
	<div class="ui container section">
		<div class="ui raised very padded segment">
			<h2>Generate a story</h2>
			<p>Random title and content will be generated by using the <a href="http://loripsum.net">loripsum.net</a> api.<br>
      You can pass custom options for the content to be generated.</p><br>
				<form class="ui form create_q" method="POST">
          <div class="field">
            <label for="fruit">Number of Paragraph</label>
            <select name='num'>
              <option value="1">1</option>
              <option value="2">2</option>
              <option value="3">3</option>
              <option value="4">4</option>
              <option value="5">5</option>
              <option value="6">6</option>
            </select>
          </div>
          <br>
          <div class="inline fields">
            <label>Paragraph length</label>
            <div class="field">
              <div class="ui radio checkbox">
                <input type="radio" name="len" value="short" checked="" tabindex="0" class="hidden">
                <label>Short</label>
              </div>
            </div>
            <div class="field">
              <div class="ui radio checkbox">
                <input type="radio" name="len" value="medium" tabindex="0" class="hidden">
                <label>Medium</label>
              </div>
            </div>
            <div class="field">
              <div class="ui radio checkbox">
                <input type="radio" name="len" value="large" tabindex="0" class="hidden">
                <label>Large</label>
              </div>
            </div>
            <div class="field">
              <div class="ui radio checkbox">
                <input type="radio" name="len" value="verylarge" tabindex="0" class="hidden">
                <label>Very Large</label>
              </div>
            </div>
          </div>
					<input type="hidden" name="token" value="<?= Token::generateToken(); ?>">
					<input type="hidden" name="action" value="generate">
          <hr>
					<br>
					<button type="submit" name="submit" class="ui button green">Submit</button>
					<a type="button" href=".." class="ui button ">Cancel</a>
				<div class="ui error message"></div>
				</form>
		</div>
	</div>
<?php include (ROOT_PATH . 'inc/footer.php'); ?>
<script>
$('.ui.radio.checkbox').checkbox();
</script>
</body>
</html>